### ISSUE TITLE
Sprite._cleanup deletes other -2x spritemaps

### ISSUE THREAD

**Issue by jagregory** [naltatis/node-sprite#5]
If you have two spritemaps being generated by a call to `sprites`, and they both have 2x versions, the 2x spritemaps will all get deleted.

In [sprite.coffee](https://github.com/naltatis/node-sprite/blob/master/lib/sprite.coffee#L112), `_cleanup`:

``` coffee
  _cleanup: (cb = ->) ->
    self = @
    fs.readdir "#{@path}", (err, files) ->
      for file in files
        if file.match("^#{self.name}-.*\.png$") and file isnt self.filename()
          fs.unlinkSync "#{self.path}/#{file}"
      cb()
```

The pattern `^#{self.name}-.*\.png` will match any -2x files that don't have the correct suffix. If you have two spritemaps being generated, each one will remove the other's output.

I assume this is trying to remove old shortsums of the current file.

**Comment by naltatis** [comment]
I've come across this problem to. This can be fixed by using another postfix for the retina folder.
I'm using "@2x" in my latest projects and have updated the README accordingly.
